// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qu-rekMBHALUseJgHUHlYk_CWxJiz1k',
    appId: '1:928028075855:web:527a957e160a1c14d5873a',
    messagingSenderId: '928028075855',
    projectId: 'act16-mad',
    authDomain: 'act16-mad.firebaseapp.com',
    storageBucket: 'act16-mad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr-ZmG5RhpxVbLYUbGrp4vyQQGZYgrWI8',
    appId: '1:928028075855:android:d271a35400834523d5873a',
    messagingSenderId: '928028075855',
    projectId: 'act16-mad',
    storageBucket: 'act16-mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCM5b94-ENjTHS_StmxOQUsPQr4PmZRmk',
    appId: '1:928028075855:ios:20a0b3c8ee57cb9fd5873a',
    messagingSenderId: '928028075855',
    projectId: 'act16-mad',
    storageBucket: 'act16-mad.firebasestorage.app',
    iosBundleId: 'com.example.act16Mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCM5b94-ENjTHS_StmxOQUsPQr4PmZRmk',
    appId: '1:928028075855:ios:20a0b3c8ee57cb9fd5873a',
    messagingSenderId: '928028075855',
    projectId: 'act16-mad',
    storageBucket: 'act16-mad.firebasestorage.app',
    iosBundleId: 'com.example.act16Mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1qu-rekMBHALUseJgHUHlYk_CWxJiz1k',
    appId: '1:928028075855:web:3dbaef8abe88f5a8d5873a',
    messagingSenderId: '928028075855',
    projectId: 'act16-mad',
    authDomain: 'act16-mad.firebaseapp.com',
    storageBucket: 'act16-mad.firebasestorage.app',
  );

}